---
- name: Build frontend image
  community.docker.docker_image:
    name: quanghuy1604/web-images
    tag: latest
    source: pull
    force_source: true

- name: Create web container
  community.docker.docker_container:
    name: "{{fe_container_name_1}}"
    image:  quanghuy1604/web-images:latest
    restart_policy: "unless-stopped"
    ports:
      - "{{fe_external_port_1}}:{{fe_internal_port_1}}"
    networks:
      - name: midterm

- name: Create web container
  community.docker.docker_container:
    name: "{{fe_container_name_2}}"
    image: quanghuy1604/web-images:latest
    restart_policy: "unless-stopped"
    ports:
      - "{{fe_external_port_2}}:{{fe_internal_port_2}}"
    networks:
      - name: midterm